#!/bin/sh

git config --global core.quotepath false

function ok () {
    echo -e "\033[0;32m[ OK ]\033[0;39m: $1"
}

function ng () {
    echo -e "\033[0;31m[ NG ]\033[0;39m: $1"
}

function warn () {
    echo -e "\033[0;33m[WARN]\033[0;39m: $1"
}

function logExec () {
    echo -e "\033[0;35m[EXEC]\033[0;39m: $1"
}

function step () {
    echo -e "\033[0;36m$1\033[0;39m"
}

function errorEnd () {
    echo "########################################"
    echo "# 異常終了"
    echo "########################################"
    exit 1
}
